//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessLogSpec) DeepCopyInto(out *AccessLogSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessLogSpec.
func (in *AccessLogSpec) DeepCopy() *AccessLogSpec {
	if in == nil {
		return nil
	}
	out := new(AccessLogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorImageSpec) DeepCopyInto(out *CollectorImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorImageSpec.
func (in *CollectorImageSpec) DeepCopy() *CollectorImageSpec {
	if in == nil {
		return nil
	}
	out := new(CollectorImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorLoggingSpec) DeepCopyInto(out *CollectorLoggingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorLoggingSpec.
func (in *CollectorLoggingSpec) DeepCopy() *CollectorLoggingSpec {
	if in == nil {
		return nil
	}
	out := new(CollectorLoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorSpec) DeepCopyInto(out *CollectorSpec) {
	*out = *in
	out.Image = in.Image
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProbeNamespaces != nil {
		in, out := &in.ProbeNamespaces, &out.ProbeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Logging = in.Logging
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorSpec.
func (in *CollectorSpec) DeepCopy() *CollectorSpec {
	if in == nil {
		return nil
	}
	out := new(CollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsolePluginLoggingSpec) DeepCopyInto(out *ConsolePluginLoggingSpec) {
	*out = *in
	out.AccessLog = in.AccessLog
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsolePluginLoggingSpec.
func (in *ConsolePluginLoggingSpec) DeepCopy() *ConsolePluginLoggingSpec {
	if in == nil {
		return nil
	}
	out := new(ConsolePluginLoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsolePluginSpec) DeepCopyInto(out *ConsolePluginSpec) {
	*out = *in
	out.Image = in.Image
	out.Logging = in.Logging
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsolePluginSpec.
func (in *ConsolePluginSpec) DeepCopy() *ConsolePluginSpec {
	if in == nil {
		return nil
	}
	out := new(ConsolePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureGateSpec) DeepCopyInto(out *FeatureGateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGateSpec.
func (in *FeatureGateSpec) DeepCopy() *FeatureGateSpec {
	if in == nil {
		return nil
	}
	out := new(FeatureGateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorEventsSpec) DeepCopyInto(out *OperatorEventsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorEventsSpec.
func (in *OperatorEventsSpec) DeepCopy() *OperatorEventsSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorEventsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorLoggingSpec) DeepCopyInto(out *OperatorLoggingSpec) {
	*out = *in
	out.Events = in.Events
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorLoggingSpec.
func (in *OperatorLoggingSpec) DeepCopy() *OperatorLoggingSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorLoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorSpec) DeepCopyInto(out *OperatorSpec) {
	*out = *in
	out.Logging = in.Logging
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorSpec.
func (in *OperatorSpec) DeepCopy() *OperatorSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvnRecon) DeepCopyInto(out *OvnRecon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvnRecon.
func (in *OvnRecon) DeepCopy() *OvnRecon {
	if in == nil {
		return nil
	}
	out := new(OvnRecon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvnRecon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvnReconList) DeepCopyInto(out *OvnReconList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OvnRecon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvnReconList.
func (in *OvnReconList) DeepCopy() *OvnReconList {
	if in == nil {
		return nil
	}
	out := new(OvnReconList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvnReconList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvnReconSpec) DeepCopyInto(out *OvnReconSpec) {
	*out = *in
	out.Operator = in.Operator
	in.ConsolePlugin.DeepCopyInto(&out.ConsolePlugin)
	in.Collector.DeepCopyInto(&out.Collector)
	out.Image = in.Image
	out.FeatureGates = in.FeatureGates
	out.CollectorImage = in.CollectorImage
	if in.CollectorProbeNamespaces != nil {
		in, out := &in.CollectorProbeNamespaces, &out.CollectorProbeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvnReconSpec.
func (in *OvnReconSpec) DeepCopy() *OvnReconSpec {
	if in == nil {
		return nil
	}
	out := new(OvnReconSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvnReconStatus) DeepCopyInto(out *OvnReconStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvnReconStatus.
func (in *OvnReconStatus) DeepCopy() *OvnReconStatus {
	if in == nil {
		return nil
	}
	out := new(OvnReconStatus)
	in.DeepCopyInto(out)
	return out
}
